### ISSUE TITLE
how to use this rich text to show the hyperlink?

### ISSUE THREAD

**Issue by chengstone** [halilozercan/compose-richtext#1]
hi, 

thanks for your amazing repo.

I would like to create a hyperlink to display in my app.

The hyper link should be embedded in a Text or similar text views like:

The last book bought is <a href='#'>this</a>

how to make that happen?

one sample image like this (https://flutter.io,  flutter github repo):

<img width="290" alt="OSmTl" src="https://user-images.githubusercontent.com/6791799/77400395-6d342780-6dee-11ea-938a-d88121de38b9.png">

**Comment by zach-klippenstein** [comment]
Unfortunately Compose doesn't support rendering links in text yet (I asked [a related question](https://kotlinlang.slack.com/archives/CJLTWPH7S/p1583794809353200) in the compose slack). I'm eagerly watching for updates on this though! This library doesn't actually support any character-level formatting just yet, although I have thoughts about what might make a nice API.

**Comment by zach-klippenstein** [comment]
Initial design for this is in #2.
