### ISSUE TITLE
Can't able to change Text Color in RichText Markdown

### ISSUE THREAD

**Issue by aiyu-ayaan** [halilozercan/compose-richtext#125]
Recently I have been working on my project and have to use markdown for my Android project and come across your Library.
The issue I faced when I turn my device in dark mode. Can you please solve this ASAP or provide me the documentation for that. 

![image](https://github.com/halilozercan/compose-richtext/assets/76834976/39f1596e-a8eb-42fd-8150-686cd5e47334)

**Comment by atulgpt** [comment]
Did you try wrapping the `BasicRichText` in `RichTextThemeProvider`? Something like below?

```kotlin
RichTextThemeProvider(
    textStyleProvider = {
        LocalTextStyle.current.copy(
            color = colorResource(id = <your color resource id>),
        )
    },
) {
    BasicRichText {
        Markdown(
            content = <markdown content>
        )
    }
}
```
