### ISSUE TITLE
Website with documentation not working

### ISSUE THREAD

**Issue by zagum** [halilozercan/compose-richtext#142]
The website [halilibo.com/compose-richtext](https://halilibo.com/compose-richtext) is currently not working. Could you fix it or copy the documentation to GitHub?

**Comment by halilozercan** [comment]
Yes, I'm aware of this problem. I had to move my domain thanks to Google Domains being deprecated 🤦‍♂️ I'll try to solve this issue conventionally by making sure the dns nameservers and records are up-to-date. If it fails, I'll just simply remove `halilibo.com` domain from my github pages and host the docs without a custom domain.

**Comment by halilozercan** [comment]
I can now access the site. Please confirm that you are able to access too so we can close this issue.

**Comment by zagum** [comment]
Yes, it's working. Thanks!
