### ISSUE TITLE
Code Viewer

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [halilozercan/compose-richtext#24]
Maybe this feature request should be for another artifact but have you thought to create a Code Viewer?

**Comment by zach-klippenstein** [comment]
Not sure what you mean, can you elaborate?

**Comment by JavierSegoviaCordoba** [comment]
Something like this but for Compose

https://github.com/PDDStudio/highlightjs-android

**Comment by halilozercan** [comment]
The rendering part shouldn't really require a new implementation. I believe [Text](https://github.com/zach-klippenstein/compose-richtext/blob/main/richtext-ui/src/main/java/com/zachklipp/richtext/ui/string/Text.kt#L46) composable is already quite capable of rendering something similar to what I've seen on `highlightjs-android`'s README screenshots. 

The actual challenge is building a `RichTextString` that is syntax highlighted. Upon my quick googling, all syntax highlighter I found are javascript based. If there is any Java or Kotlin libraries available for such a task, the rest should be rather easy.

**Comment by zach-klippenstein** [comment]
Yep, then we just need a way to plug it in. https://github.com/zach-klippenstein/compose-richtext/pull/20#discussion_r517568941

**Comment by LouisCAD** [comment]
Kotlin has an official ANTLR spec: https://github.com/Kotlin/kotlin-spec

Maybe this can help to feed to an ANTLR parser if it's not overkill?

Also, I found this article that might be helpful: [How to create an editor with syntax highlighting for your language using ANTLR and Kotlin](https://tomassetti.me/how-to-create-an-editor-with-syntax-highlighting-dsl/) and

**Comment by zach-klippenstein** [comment]
This library shouldn't ever be in the business of parsing. It should make it possible to wire up existing parsers to rendering, and maybe even provide a few such wirings out of the box (as in the CommonMark example).
