### ISSUE TITLE
Are there any plans to update to newer compose versions?

### ISSUE THREAD

**Issue by LouisCAD** [halilozercan/compose-richtext#29]

**Comment by zach-klippenstein** [comment]
Yes, I just haven't had time to do so in a few weeks. If this is blocking you, I'd be happy to review a PR, but I can't guarantee when I'll be able to get around to updating it myself at this point.

**Comment by LouisCAD** [comment]
Hello, with Compose now in beta, I think it's the right time to upgrade that library.

Can you post a comment if you start working on that?
I'm quite backlogged right now, but if I find time in the upcoming weeks, I might attempt doing it, but I don't want to overlap and have the effort be done twice.

**Comment by zach-klippenstein** [comment]
I'm hoping to tackle the upgrade this weekend.

**Comment by LouisCAD** [comment]
I've seen the 0.2.0 release for Compose beta1, so this is resolved. Thank you for that!
