### ISSUE TITLE
InlineContent for RichTextString should expose PlaceholderVerticalAlign parameter

### ISSUE THREAD

**Issue by halilozercan** [halilozercan/compose-richtext#33]
Currently this parameter is hard-coded to `AboveBaseline`. However, a user might want to use `Text` as inline content and align the baseline between this inline-content and the line that it stands in. 

Basically, changing `InlineContent` class to

```
public class InlineContent(
  internal val initialSize: (Density.() -> IntSize)? = null,
  internal val placeholderVerticalAlign: PlaceholderVerticalAlign = AboveBaseline,
  internal val content: @Composable Density.(alternateText: String) -> Unit
)
```
should suffice, granted that this new parameter is also passed while creating Placeholder.

**Comment by zach-klippenstein** [comment]
SG
