### ISSUE TITLE
RichTextStyle ignores initial stringStyle: RichTextStringStyle

### ISSUE THREAD

**Issue by halilozercan** [halilozercan/compose-richtext#34]
RichText initiates everything with a `merge` call on an empty `RichTextStyle` with the received style from user. However, specific `merge` function for `RichTextStringStyle` looks like this

```
stringStyle = stringStyle?.merge(otherStyle?.stringStyle)
``` 
If initially (by default yes) stringStyle is null, it can never merge with the `otherStyle` and remain as null.

Would this work?
```
stringStyle = stringStyle?.merge(otherStyle?.stringStyle) ?: otherStyle?.stringStyle
```

**Comment by zach-klippenstein** [comment]
LGTM
