### ISSUE TITLE
Enable https for the documentation website

### ISSUE THREAD

**Issue by LouisCAD** [halilozercan/compose-richtext#38]
Hello, I think ensuring SSL is used for the doc website is a low hanging fruit and ensures the page content can not get tampered with via MITM (machine/man in the middle).

It should just be a checkbox to tick in the GitHub project settings.

**Comment by halilozercan** [comment]
new documentation site has https enabled :)

[https://halilibo.com/compose-richtext](https://halilibo.com/compose-richtext)
