### ISSUE TITLE
Add support for scrolling Markdown code blocks

### ISSUE THREAD

**Issue by ZianeA** [halilozercan/compose-richtext#56]
Currently, Markdown code blocks wrap lines by default. It would be nice if we could customize that behavior. 

https://user-images.githubusercontent.com/14791787/132881882-14522c3c-0a8a-465c-b6fd-43f3e72cb768.mp4

**Comment by halilozercan** [comment]
I actually had a CodeBlock implementation that had line numbers and horizontal scrolling(disabled word wrapping). Let me find it :)
