### ISSUE TITLE
No compose previews and images are not supported? 

### ISSUE THREAD

**Issue by falcon4ever** [halilozercan/compose-richtext#65]
1. It seems like there are no Compose Previews when trying to use this Compose component (see screenshot)
2. If we provide markdown with an image component in it ( https://www.markdownguide.org/basic-syntax/#images-1 ), it stops rendering early.

<img width="1910" alt="Screen Shot 2021-09-28 at 4 59 10 PM" src="https://user-images.githubusercontent.com/480019/135164883-20fdd6a7-2004-4629-a682-e5536423f7dc.png">

**Comment by halilozercan** [comment]
1. I know this has been an issue for some time. Currently, I have really no idea what is causing this. I'm mostly suspicious of Commonmark library. I'll need to learn more about how Previews work in Compose to solve this error.
2. Are you sure your app has Internet permission? Same URL work on the demo app for me.

**Comment by MoveUpwardsDev** [comment]
@halilozercan I face the same issue regarding `RemoteImage` and loading remote image. I test the same in the demo app and it works as expected. My project include Coil library as well but in version 2.0.0 to have access to the `AsyncImage` composable. Maybe the two library version collapse.

**Comment by bstoker** [comment]
> 2. If we provide markdown with an image component in it ( https://www.markdownguide.org/basic-syntax/#images-1 ), it stops rendering early.

I'm facing the same issue in the demo app when you remove the title from the image markdown:
```
![random image](https://picsum.photos/seed/picsum/400/400)
```
Is there any update yet on this issue?

Edit: Put up a [pull request](https://github.com/halilozercan/compose-richtext/pull/78) myself that fixed the issue.
