### ISSUE TITLE
Can't import RichTextThemeIntegration composable function

### ISSUE THREAD

**Issue by GerardPaligot** [halilozercan/compose-richtext#76]
Because there is a data class with the same name in the same scope visibility, we can't import `RichTextThemeIntegration` composable function, the data class take the priority.

We should rename the data class or the data class.

**Comment by GerardPaligot** [comment]
If I give a value for each parameter, there is no more error.
I think that could be a good idea to rename one of them but I let you decide.

**Comment by halilozercan** [comment]
Data class should be internal. Where are you calling `RichTextThemeIntegration` from? This doesn't create a problem in richtext-ui-material module.

**Comment by GerardPaligot** [comment]
When you fill all parameters, it found the composable but when I write the signature of `RichTextThemeIntegration` for the first time without its parameters, it can't find the correct class/function to import.

However, I tried to reproduce just now and everything work fine... Maybe it was simply an IDE caching issue?!

I close the issue. If someone else meet the same behavior, that could be interesting to investigate.
