### ISSUE TITLE
Markdown link color shouldn't be arbitrary modified/averaged

### ISSUE THREAD

**Issue by radek606** [halilozercan/compose-richtext#88]
If I set particular color in link style for markdown, I expect it to be displayed as defined. Color modification should be at most an option you can choose, not arbitrary internal action.

**Comment by bpappin** [comment]
This is causing us a whole lot of trouble.
I'm hearing trying to figure out if I have to drop this library or if I can find a workaround.

**Comment by bpappin** [comment]
Submitted PR https://github.com/halilozercan/compose-richtext/pull/90 for this. its a brute force approach, but will give us what we need, and still allow anyone depending on this "feature" to enable it.
