### ISSUE TITLE
Using an alpha version of the AGP

### ISSUE THREAD

**Issue by bpappin** [halilozercan/compose-richtext#89]
When you check out and try to build, you get this error:

"The project is using an incompatible version (AGP 7.4.0-alpha01) of the Android Gradle plugin. Latest supported version is AGP 7.2.2"

Unless using the alpha is somehow critical to the library, the AGP should be compatible with the latest, but not some alpha version.

**Comment by halilozercan** [comment]
This is no longer an issue since the library only uses the latest stable multiplatform releases.
