### ISSUE TITLE
Bug with empty list item 

### ISSUE THREAD

**Issue by akishind-medlinx** [halilozercan/compose-richtext#96]
Hello! There seems to be a visual bug when there is en empty item in the list, for the text after the list. For example
```kotlin
MaterialRichText(style = null) {
    Markdown(
        content = "List\n* item1\n* \n* item2\n\nSome text",
        onLinkClicked = null
    )
}
```
produces this result: 
![image](https://user-images.githubusercontent.com/108879706/194810520-c6078a76-575d-4f2f-a9e5-3f718ed46ba2.png)

This is the expected result (I added a non-breaking space for the empty item):
![image](https://user-images.githubusercontent.com/108879706/194810658-b698c58e-f9b6-4a66-85f5-b71c16c358a2.png)

Can you tell me, is it caused by a bug in the library? Or is this a problem with the Markdown itself, and its specification?

**Comment by atulgpt** [comment]
<img width="1033" alt="Screenshot 2024-01-16 at 4 27 59 PM" src="https://github.com/halilozercan/compose-richtext/assets/11026203/e27227c5-903e-4484-84ad-cd93b5ba4836">

Rendering this in https://spec.commonmark.org/dingus/ produces the correct result this seems like the bug in this library code
